### PR TITLE
[WIP] Landing Page

### PR DESCRIPTION
**Pull request by lrlna**
Added installation instructions, and a little blurb about what yargs is that I got from this [original commit](https://github.com/bcoe/yargs/commit/54e31d505f820b80af13644e460894b320bf25a3) :speak_no_evil: 

What do you pals think of wording/those boxes/pink code highlight? (I am starting to feel there is too much pink, and this may be the last pink I do on this page :astonished: )

screenshot - 16-01-15 - 11 12 48 pm

Up next:

- [x] **Landing page**. Write up a good example. Should walk a visitor through setting up a basic `option` and `argument`, but maybe not a `command` just yet? 
- [ ] **Landing page**. Get a list of 3/4 cool projects that use yargs and get their watermark.
- [ ] **Community page**. Related libraries.
- [ ] **Community page**. Contributing [guidelines](https://github.com/bcoe/yargs/blob/master/contributing.md).
- [ ] **Examples page**. Add a detailed tutorial of how to use this. I am thinking something silly to start with; like this [wombat](https://github.com/lrlna/wombat.js), but sub the wombat for a pirate to be more relatable to yargs. We should be able to add more tutorials as we go, and update to `4.x`. 

cc/ @bcoe @nexdrew @maxrimue

### CODE REVIEW

**Comment by lrlna** [comment]
hmmm actually scratch that wombat :koala: module. I thought I used a lot more than a boolean there, but apparently not :hear_no_evil: :speak_no_evil: :see_no_evil:

**Comment by maxrimue** [comment]
First of all, great work @lrlna. For the installation part, I would prefer something like
> Open your terminal, go to your project, and run using npm:
> npm install --save yargs   

Just because the current text could be confusing to people that are new to npm.   
   
I'm also not quite sure about the "What's Yargs?" text. I like the content itself, I'm just not sure if this should also be Pirate English? As part of version 4.x of yargs, we already were considering rewriting the `readme.md` to get rid of _some_ Pirate English, perhaps here the header (which I love btw) is already enough of it. It's the most critical text on the site and therefore should be understood by any visitor, we need to consider people not understanding the text that aren't capable of understanding Pirate English. It's just my personal opinion though, what do the others think? Should Pirate English just be treated as a little "touch" to the site, or should it appear throughout?

**Comment by lrlna** [comment]
@maxrimue Those are the exact two point I kept going back and forth about. 

Personally I find it hard to read pirate english (i.e. what are hearties?); it takes me a couple of takes. I didn't want to be the party pooper and write this in regular english when no-one else wanted to haha :sweat_smile: I could see having a few little touches of `yer`, and `yar` though.

**Comment by lrlna** [comment]
@bcoe in terms of vertical height. Is this better? it's at `65vh` instead of `75vh`.
screenshot - 16-01-16 - 11 12 15 am

**Comment by lrlna** [comment]
Description attempt numero uno: 

>>> Yargs is a command line argument parsing library. It helps you define options, arguments, and commands you want to accept in your application. In the meantime, you can focus on building out your program's functionality. As you build out your application, you are able to access the arguments from the object yargs created for you.

**Comment by bcoe** [comment]
@lrlna this work is looking wonderful, some feedback:

1. I like `description attempt numero uno`, but I'd be tempted for us to outline that yargs doesn't just parse your arguments, but automatically generates an elegant UI for your CLI application -- this is one of the main things that distinguishes it from, say, `minimist`.
2. perhaps rather than `install` we could have an identical looking section that is instead labeled `quick start`, I'm picturing:

```sh
npm install yargs --save
```

```js
#!/usr/bin/env node

#!/usr/bin/env node

require('./')
  .usage('$0 <cmd> [args]')
  .option('name', {
    alias: 'n',
    describe: 'provide yer name!'
  })
  .command('hello', 'welcome ter yargs!', function (yargs, argv) {
    console.log('hello', argv.name, 'welcome to yargs!')
  })
  .help('help')
  .argv
```

```sh
node example.js --help

test <cmd> [args]

Commands:
  hello  welcome ter yargs!

Options:
  --name, -n  provide yer name!
  --help      Show help                                                [boolean]
```

```sh
node example.js hello --name Iriana
hello Irina welcome to yargs!
```

Just some thoughts, please modify; what's the minimal example we should show?

**Comment by lrlna** [comment]
@bcoe definitely agree we need something about our awesome UI and :100: user experience. Trying this:

>Yargs helps you build interactive command line user experiences, starting with parsing your arguments, and ending with generating an elegant UI for your CLI application. Yargs is a command line argument parsing library. It helps you define options, arguments, and commands you want to accept in your application. As you build out your application, you are able to access the arguments from the object yargs created for you.
> Yargs is an better-user-experience library. It comes with built in help menu based on your arguments, command completion, and ways to write descriptions for your arguments to guide your users through your applicaiton. Yargs essentially allows you to focus on building out your program's functionality without worrying about your arguments. 

I am pretty happy with paragraph 1. Paragraph 2 is still pretty iffy. I'll think about it some more. 

As for quick start, I think we should have that below all this maybe? In case some people just need a quick reminder and then they jump straight to the docs? Or nah?
I made a branch [feature/example](https://github.com/yargs/yargs.github.io/tree/feature/example) just for that :koala: :tiger:

**Comment by lrlna** [comment]
hi! I've merged the `getting started` portion with example into this branch to keep it all together. It doesn't quite look as nice and sleek as it should be, but it's good to take a look at and see if we need anything adjusted.

**Comment by lrlna** [comment]
When I scroll, it looks like so: 
20160127-100441_capture

**Comment by maxrimue** [comment]
I thought perhaps we could structure the introduction text a bit more? I was thinking of something like this:

>Yargs helps you build interactive command line user experiences, starting with parsing arguments, and ending with generating an elegant UI for your CLI application. 

>Yargs is an better-user-experience library. It comes with
>- commands and (grouped) options (like `module run -n --force`)
>- a dynamically generated help menu based on your arguments,
>- command completion
>- ways to write descriptions for your arguments to guide your users through your application,
and more.

>Yargs essentially allows you to focus on building out your program's functionality without worrying about your arguments.

Maybe a feature list would be better instead of a long text? Obviously not this one, but I'm sure we could create a good one :smile: 

Just like it is now, I prefer introduction before quick start. First look at what it is, then how it works, makes sense to me.

**Comment by lrlna** [comment]
Ok, I think this description is getting good. Using @maxrimue excellent wording above :ok_hand: :

> Yargs helps you build interactive command line user experiences by parsing arguments and generating an elegant user interface for your command line application so you don't have to. 

Yargs is an better-user-experience library. It comes with:

* commands and (grouped) options (like module run -n --force),
* a dynamically generated help menu based on your arguments,
* bash-completion shortcuts for commands and options,
* and much more.

With the above functionalities, yargs allows you to focus on building out your program without worrying about your arguments.

**Comment by lrlna** [comment]
20160207-115224_capture
We look like so now.

**Pull request merged**
