### PR TITLE
Fix/media query

### PR DESCRIPTION
**Pull request by lrlna**

### CODE REVIEW

**Comment by bcoe** [comment]
dog

**Comment by bcoe** [comment]
@lrlna in all seriousness though, this looks great; it's nice that you get scss as part of Jekyll's build process.

**Comment by lrlna** [comment]
bahahahah that *does* look like me hmphhh :thought_balloon: 

but yeah, really glad a bunch of this is already pre-written o.O

**Comment by bcoe** [comment]
@lrlna for the record, the dog represents me.

**Pull request merged**
